

http://localhost/api/appointments?from=2000-01-01&to=2030-01-01
Accept: application/json

###

POST http://localhost/api/appointments
Content-Type: application/json
Accept: application/json

{
    "clientName": "some name",
    "start": "2023-09-13T07:00:00.000Z",
    "end": "2023-09-13T09:00:00.000Z"

}
